# Generated by Django 5.2.17 on 2026-09-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='الاسم الأول'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='اسم العائلة'),
        ),
    ]
