# Generated by Django 5.2.17 on 2026-08-27 15:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='اسم التقييم')),
                ('assessment_type', models.CharField(choices=[('exam', 'اختبار'), ('project', 'مشروع')], max_length=20, verbose_name='نوع التقييم')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الدرجة النهائية')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.classroom', verbose_name='الفصل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.subject', verbose_name='المادة')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='schools.term', verbose_name='الترم')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الدرجة')),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessments.assessment', verbose_name='التقييم')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_grades', to=settings.AUTH_USER_MODEL, verbose_name='سجلها')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.studentprofile', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'درجة',
                'verbose_name_plural': 'الدرجات',
                'constraints': [models.UniqueConstraint(fields=('assessment', 'student'), name='unique_grade_per_student_assessment')],
            },
        ),
    ]
