# Generated by Django 5.2.17 on 2026-09-15 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('background', models.ImageField(upload_to='certificate_templates/')),
                ('width', models.PositiveIntegerField(default=2480)),
                ('height', models.PositiveIntegerField(default=3508)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
