# Generated by Django 5.2.17 on 2026-09-15 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('student_name', 'Student Name'), ('student_id', 'Student ID'), ('class_name', 'Class'), ('academic_year', 'Academic Year'), ('total', 'Total'), ('percentage', 'Percentage'), ('result', 'Result'), ('attendance', 'Attendance'), ('date', 'Date')], max_length=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('font_size', models.PositiveIntegerField(default=40)),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('font_name', models.CharField(default='Arial', max_length=100)),
                ('is_bold', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='certificates.certificatetemplate')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
