# Generated by Django 5.2.17 on 2026-09-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificatefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatefield',
            name='height',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='certificatefield',
            name='width',
            field=models.FloatField(default=500),
        ),
    ]
