# Generated by Django 5.2.17 on 2026-08-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المدرسة')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='الرابط المختصر')),
                ('is_active', models.BooleanField(default=True, verbose_name='المدرسة مفعلة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مدرسة',
                'verbose_name_plural': 'المدارس',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم العام الدراسي')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_current', models.BooleanField(default=False, verbose_name='العام الحالي')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='schools.school')),
            ],
            options={
                'verbose_name': 'عام دراسي',
                'verbose_name_plural': 'الأعوام الدراسية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الترم')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_current', models.BooleanField(default=False, verbose_name='الترم الحالي')),
                ('is_closed', models.BooleanField(default=False, verbose_name='مغلق')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='schools.academicyear', verbose_name='العام الدراسي')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='schools.school')),
            ],
            options={
                'verbose_name': 'ترم',
                'verbose_name_plural': 'الترمات',
                'ordering': ['start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_academic_year_per_school'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'name'), name='unique_term_per_year'),
        ),
    ]
