# Generated by Django 5.2.17 on 2026-08-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('exam', 'اختبار'), ('project', 'مشروع')], max_length=20, verbose_name='نوع التقييم')),
                ('max_count', models.PositiveIntegerField(default=1, verbose_name='عدد التقييمات المسموح بها')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='الوزن')),
            ],
            options={
                'verbose_name': 'نظام توزيع الدرجات',
                'verbose_name_plural': 'أنظمة توزيع الدرجات',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='كود المادة')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'إسناد تدريس',
                'verbose_name_plural': 'إسنادات التدريس',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفصل')),
                ('grade_level', models.PositiveIntegerField(verbose_name='الصف الدراسي')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='schools.academicyear', verbose_name='العام الدراسي')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'الفصول',
                'ordering': ['grade_level', 'name'],
            },
        ),
    ]
