# Generated by Django 5.2.17 on 2026-09-05 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'مادة الفصل',
                'verbose_name_plural': 'مواد الفصول',
                'ordering': ['classroom__grade_level', 'classroom__name', 'subject__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='gradescheme',
            options={'verbose_name': 'نظام درجات', 'verbose_name_plural': 'أنظمة الدرجات'},
        ),
        migrations.AlterModelOptions(
            name='teachingassignment',
            options={'verbose_name': 'تكليف تدريسي', 'verbose_name_plural': 'التكليفات التدريسية'},
        ),
        migrations.RemoveConstraint(
            model_name='gradescheme',
            name='unique_grade_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='teachingassignment',
            name='unique_teacher_class_subject',
        ),
        migrations.AddField(
            model_name='gradescheme',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='grade_schemes', to='academics.classroom', verbose_name='الفصول'),
        ),
        migrations.AlterField(
            model_name='gradescheme',
            name='max_count',
            field=models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى لعدد التقييمات'),
        ),
        migrations.AlterField(
            model_name='gradescheme',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الوزن'),
        ),
        migrations.AddConstraint(
            model_name='gradescheme',
            constraint=models.UniqueConstraint(fields=('school', 'subject', 'assessment_type'), name='unique_grade_scheme_per_subject_type'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('school', 'classroom', 'subject'), name='unique_teacher_per_classroom_subject'),
        ),
        migrations.AddField(
            model_name='classroomsubject',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_subjects', to='academics.classroom', verbose_name='الفصل'),
        ),
        migrations.AddField(
            model_name='classroomsubject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='schools.school'),
        ),
        migrations.AddField(
            model_name='classroomsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_subjects', to='academics.subject', verbose_name='المادة'),
        ),
        migrations.AddConstraint(
            model_name='classroomsubject',
            constraint=models.UniqueConstraint(fields=('school', 'classroom', 'subject'), name='unique_classroom_subject_per_school'),
        ),
    ]
