# Generated by Django 5.2.17 on 2026-09-05 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classroomsubject_alter_gradescheme_options_and_more'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroomsubject',
            options={'ordering': ['classroom', 'subject'], 'verbose_name': 'مادة الفصل', 'verbose_name_plural': 'مواد الفصول'},
        ),
        migrations.AlterModelOptions(
            name='teachingassignment',
            options={'ordering': ['classroom', 'subject'], 'verbose_name': 'تكليف تدريسي', 'verbose_name_plural': 'التكليفات التدريسية'},
        ),
        migrations.RemoveConstraint(
            model_name='classroomsubject',
            name='unique_classroom_subject_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='gradescheme',
            name='unique_grade_scheme_per_subject_type',
        ),
        migrations.RemoveConstraint(
            model_name='teachingassignment',
            name='unique_teacher_per_classroom_subject',
        ),
        migrations.AlterField(
            model_name='gradescheme',
            name='max_count',
            field=models.PositiveIntegerField(verbose_name='عدد التقييمات'),
        ),
        migrations.AlterField(
            model_name='gradescheme',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الوزن'),
        ),
        migrations.AddConstraint(
            model_name='classroomsubject',
            constraint=models.UniqueConstraint(fields=('school', 'classroom', 'subject'), name='unique_classroom_subject'),
        ),
        migrations.AddConstraint(
            model_name='gradescheme',
            constraint=models.UniqueConstraint(fields=('school', 'subject', 'assessment_type'), name='unique_grade_scheme_subject_type'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('school', 'classroom', 'subject'), name='unique_classroom_subject_teacher'),
        ),
    ]
