# Generated by Django 5.2.17 on 2026-09-05 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_classroomsubject_options_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم النظام')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('classrooms', models.ManyToManyField(blank=True, related_name='academic_schemes', to='academics.classroom', verbose_name='الفصول')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='schools.school')),
                ('subjects', models.ManyToManyField(blank=True, related_name='academic_schemes', to='academics.subject', verbose_name='المواد')),
            ],
            options={
                'verbose_name': 'نظام أكاديمي',
                'verbose_name_plural': 'الأنظمة الأكاديمية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicSchemeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('exam', 'اختبار'), ('project', 'مشروع')], max_length=20, verbose_name='نوع التقييم')),
                ('max_count', models.PositiveIntegerField(verbose_name='عدد التقييمات')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الوزن')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='academics.academicscheme', verbose_name='النظام الأكاديمي')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='schools.school')),
            ],
            options={
                'verbose_name': 'قاعدة درجات',
                'verbose_name_plural': 'قواعد الدرجات',
                'ordering': ['scheme', 'assessment_type'],
                'constraints': [models.UniqueConstraint(fields=('school', 'scheme', 'assessment_type'), name='unique_scheme_rule_type')],
            },
        ),
    ]
