# Generated by Django 5.2.17 on 2026-08-27 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('excused', 'بعذر')], default='present', max_length=10, verbose_name='الحالة')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.classroom', verbose_name='الفصل')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL, verbose_name='سجلها')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.studentprofile', verbose_name='الطالب')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='schools.term', verbose_name='الترم')),
            ],
            options={
                'verbose_name': 'حضور',
                'verbose_name_plural': 'الحضور',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='unique_student_attendance_per_day')],
            },
        ),
    ]
